name: Bug report
description: Report a clearly broken feature
title: "bug: "
labels: ["bug", "triage"]
assignees:
  - osuAkatsuki/bancho-py-devs
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue!
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Do `...` thing
        2. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: bpy-version
    attributes:
      label: bancho.py Version
      description: What version of bancho.py are you running?
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of python are you using?
      options:
        - 3.9.X (Default)
        - 3.10.X
        - 3.11.X
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
